# Site settings
title: Zenergy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Wij, leden van Zenergy, hebben een doel. Wij maken onze school iedere dag een stukje zuiniger zodat we uiteindelijk een school zijn die zich bewust is van het energieverbruik.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zernergy.github.io" # the base hostname & protocol for your site
twitter_username: ---
github_username:  ---

# Build settings
markdown: kramdown

# Social
links:
    twitter: zenergy2015
    facebook: ZenergyChallenge
    instagram: ZenergyChallenge
    github: 
    pinterest: 
    youtube:
    linkedin:
    flickr:
    email: jasperwr@live.com
    dropbox: 

# Content
home:
    block1: >
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
        
    block2: >
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
        
    block3: >
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
        
    info: >
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
            
collapsible:
 - header: Sterren?
   info: >
            Tijdens de Energy Challenge is het de bedoeling dat je de opdrachten zo goed mogelijk uitvoert. Als een school een opdracht goed heeft uitgevoerd kan de school daar een ster voor krijgen. Deze sterren heb je nodig om de Challenge te winnen. Er zijn zeven sterren te verdienen bij de zeven stappen die je volgt gedurende de Challenge. De Energy Challenge is in drie delen verdeeld.  
            
 - header: Fase 1
   info: >
            In het eerste deel, de voorbereiding, zijn er twee sterren te verdienen. Tijdens de voorbereiding maken de scholen een logo, een filmpje en een plan van aanpak.  
 - header: Fase 2
   info: >
            Tijdens het tweede deel van de Challenge is het de bedoeling om het plan van aanpak uit te voeren, de ouders erbij te betrekken, en via sociale media nog meer mensen te stimuleren om ook zuiniger met energie om te gaan. Hiervoor zijn dan ook drie sterren te verdienen. Er is ook nog een afsluiting waarop we terugblikken op de Energy Challenge. 
 - header: Fase 3
   info: >
            Er wordt dan een event voor de ouders georganiseerd en er wordt gekeken of de Challenge energie heet bespaard bij de scholen. Hiervoor zijn nog eens twee sterren te verdienen. De school die tijdens de drie fases de meeste sterren heeft verdiend maakt een grote kans om de hoofdprijs te winnen. De jury kijkt niet alleen naar het aantal behaalde sterren. Er wordt ook gelet op manier hoe ze behaald zijn. Hierbij kijken ze naar vijf punten: Presentatie, effectiviteit, creativiteit, actieve volgers en de inhoud van de campagne. Er zijn tijdens de opdrachten, naast de sterren, ook nog kleinere prijzen te winnen. Welke prijzen er worden uitgereikt is nog niet bekent. In Drenthe doen negenentwintig basisscholen en middelbare scholen mee aan de Challenge. Er is dus genoeg concurrentie om tegen te strijden!
    

agenda:
 - date: 12 Juni 2015
   event: Finale Energy Challenges Drenthe



            
